// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createPayoutStmt, err = db.PrepareContext(ctx, createPayout); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePayout: %w", err)
	}
	if q.getPayoutStmt, err = db.PrepareContext(ctx, getPayout); err != nil {
		return nil, fmt.Errorf("error preparing query GetPayout: %w", err)
	}
	if q.listPayoutsStmt, err = db.PrepareContext(ctx, listPayouts); err != nil {
		return nil, fmt.Errorf("error preparing query ListPayouts: %w", err)
	}
	if q.listPayoutsByBatchIDStmt, err = db.PrepareContext(ctx, listPayoutsByBatchID); err != nil {
		return nil, fmt.Errorf("error preparing query ListPayoutsByBatchID: %w", err)
	}
	if q.updatePayoutStatusStmt, err = db.PrepareContext(ctx, updatePayoutStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePayoutStatus: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createPayoutStmt != nil {
		if cerr := q.createPayoutStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPayoutStmt: %w", cerr)
		}
	}
	if q.getPayoutStmt != nil {
		if cerr := q.getPayoutStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPayoutStmt: %w", cerr)
		}
	}
	if q.listPayoutsStmt != nil {
		if cerr := q.listPayoutsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPayoutsStmt: %w", cerr)
		}
	}
	if q.listPayoutsByBatchIDStmt != nil {
		if cerr := q.listPayoutsByBatchIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPayoutsByBatchIDStmt: %w", cerr)
		}
	}
	if q.updatePayoutStatusStmt != nil {
		if cerr := q.updatePayoutStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePayoutStatusStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                       DBTX
	tx                       *sql.Tx
	createPayoutStmt         *sql.Stmt
	getPayoutStmt            *sql.Stmt
	listPayoutsStmt          *sql.Stmt
	listPayoutsByBatchIDStmt *sql.Stmt
	updatePayoutStatusStmt   *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                       tx,
		tx:                       tx,
		createPayoutStmt:         q.createPayoutStmt,
		getPayoutStmt:            q.getPayoutStmt,
		listPayoutsStmt:          q.listPayoutsStmt,
		listPayoutsByBatchIDStmt: q.listPayoutsByBatchIDStmt,
		updatePayoutStatusStmt:   q.updatePayoutStatusStmt,
	}
}
