// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreatePayout(ctx context.Context, arg CreatePayoutParams) (Payout, error)
	GetPayout(ctx context.Context, id string) (Payout, error)
	ListPayouts(ctx context.Context) ([]Payout, error)
	ListPayoutsByBatchID(ctx context.Context, batchID sql.NullString) ([]Payout, error)
	UpdatePayoutStatus(ctx context.Context, arg UpdatePayoutStatusParams) error
}

var _ Querier = (*Queries)(nil)
